"""initial migration

Revision ID: a9368b077657
Revises: 
Create Date: 2026-03-25 15:27:06.729905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a9368b077657'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_channel_id'), 'channels', ['channel_id'], unique=True)
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_table('lifecycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_vida', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('cesionario', sa.String(length=200), nullable=True),
    sa.Column('vendedor', sa.String(length=200), nullable=True),
    sa.Column('canal', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lifecycle_contact_id', 'lifecycles', ['contact_id'], unique=False)
    op.create_index('idx_lifecycle_fecha_ciclo', 'lifecycles', ['fecha', 'ciclo_vida'], unique=False)
    op.create_index(op.f('ix_lifecycles_ciclo_vida'), 'lifecycles', ['ciclo_vida'], unique=False)
    op.create_index(op.f('ix_lifecycles_contact_id'), 'lifecycles', ['contact_id'], unique=False)
    op.create_index(op.f('ix_lifecycles_fecha'), 'lifecycles', ['fecha'], unique=False)
    op.create_index(op.f('ix_lifecycles_id'), 'lifecycles', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_team_id'), 'teams', ['team_id'], unique=True)
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('agente_id', sa.Integer(), nullable=True),
    sa.Column('ad_timestamp', sa.DateTime(), nullable=True),
    sa.Column('ad_channel_id', sa.String(length=50), nullable=True),
    sa.Column('ad_channel_type', sa.String(length=50), nullable=True),
    sa.Column('ad_contact_type', sa.String(length=50), nullable=True),
    sa.Column('ad_adset_id', sa.String(length=100), nullable=True),
    sa.Column('ad_adset_name', sa.String(length=200), nullable=True),
    sa.Column('ad_ad_url', sa.String(length=500), nullable=True),
    sa.Column('ad_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ads_adset_name', 'ads', ['ad_adset_name'], unique=False)
    op.create_index('idx_ads_timestamp', 'ads', ['ad_timestamp'], unique=False)
    op.create_index(op.f('ix_ads_ad_adset_name'), 'ads', ['ad_adset_name'], unique=False)
    op.create_index(op.f('ix_ads_ad_timestamp'), 'ads', ['ad_timestamp'], unique=False)
    op.create_index(op.f('ix_ads_agente_id'), 'ads', ['agente_id'], unique=False)
    op.create_index(op.f('ix_ads_contact_id'), 'ads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_ads_id'), 'ads', ['id'], unique=False)
    op.create_table('closed_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('canal_id', sa.Integer(), nullable=True),
    sa.Column('cesionario_id', sa.Integer(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('tipificacion', sa.String(length=200), nullable=True),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['canal_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['cesionario_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_closed_fecha_canal', 'closed_conversations', ['fecha', 'canal_id'], unique=False)
    op.create_index('idx_closed_fecha_equipo', 'closed_conversations', ['fecha', 'equipo_id'], unique=False)
    op.create_index(op.f('ix_closed_conversations_canal_id'), 'closed_conversations', ['canal_id'], unique=False)
    op.create_index(op.f('ix_closed_conversations_cesionario_id'), 'closed_conversations', ['cesionario_id'], unique=False)
    op.create_index(op.f('ix_closed_conversations_contact_id'), 'closed_conversations', ['contact_id'], unique=False)
    op.create_index(op.f('ix_closed_conversations_equipo_id'), 'closed_conversations', ['equipo_id'], unique=False)
    op.create_index(op.f('ix_closed_conversations_fecha'), 'closed_conversations', ['fecha'], unique=False)
    op.create_index(op.f('ix_closed_conversations_id'), 'closed_conversations', ['id'], unique=False)
    op.create_table('csat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('csat_score', sa.Integer(), nullable=False),
    sa.Column('cesionario_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('tiempo_resolucion', sa.Integer(), nullable=True),
    sa.Column('tipificacion', sa.String(length=200), nullable=True),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cesionario_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_csat_agent', 'csat', ['cesionario_id'], unique=False)
    op.create_index('idx_csat_fecha', 'csat', ['fecha'], unique=False)
    op.create_index(op.f('ix_csat_cesionario_id'), 'csat', ['cesionario_id'], unique=False)
    op.create_index(op.f('ix_csat_contact_id'), 'csat', ['contact_id'], unique=False)
    op.create_index(op.f('ix_csat_fecha'), 'csat', ['fecha'], unique=False)
    op.create_index(op.f('ix_csat_id'), 'csat', ['id'], unique=False)
    op.create_index(op.f('ix_csat_team_id'), 'csat', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_csat_team_id'), table_name='csat')
    op.drop_index(op.f('ix_csat_id'), table_name='csat')
    op.drop_index(op.f('ix_csat_fecha'), table_name='csat')
    op.drop_index(op.f('ix_csat_contact_id'), table_name='csat')
    op.drop_index(op.f('ix_csat_cesionario_id'), table_name='csat')
    op.drop_index('idx_csat_fecha', table_name='csat')
    op.drop_index('idx_csat_agent', table_name='csat')
    op.drop_table('csat')
    op.drop_index(op.f('ix_closed_conversations_id'), table_name='closed_conversations')
    op.drop_index(op.f('ix_closed_conversations_fecha'), table_name='closed_conversations')
    op.drop_index(op.f('ix_closed_conversations_equipo_id'), table_name='closed_conversations')
    op.drop_index(op.f('ix_closed_conversations_contact_id'), table_name='closed_conversations')
    op.drop_index(op.f('ix_closed_conversations_cesionario_id'), table_name='closed_conversations')
    op.drop_index(op.f('ix_closed_conversations_canal_id'), table_name='closed_conversations')
    op.drop_index('idx_closed_fecha_equipo', table_name='closed_conversations')
    op.drop_index('idx_closed_fecha_canal', table_name='closed_conversations')
    op.drop_table('closed_conversations')
    op.drop_index(op.f('ix_ads_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_contact_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_agente_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_ad_timestamp'), table_name='ads')
    op.drop_index(op.f('ix_ads_ad_adset_name'), table_name='ads')
    op.drop_index('idx_ads_timestamp', table_name='ads')
    op.drop_index('idx_ads_adset_name', table_name='ads')
    op.drop_table('ads')
    op.drop_index(op.f('ix_teams_team_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_lifecycles_id'), table_name='lifecycles')
    op.drop_index(op.f('ix_lifecycles_fecha'), table_name='lifecycles')
    op.drop_index(op.f('ix_lifecycles_contact_id'), table_name='lifecycles')
    op.drop_index(op.f('ix_lifecycles_ciclo_vida'), table_name='lifecycles')
    op.drop_index('idx_lifecycle_fecha_ciclo', table_name='lifecycles')
    op.drop_index('idx_lifecycle_contact_id', table_name='lifecycles')
    op.drop_table('lifecycles')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_channel_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
